### ISSUE TITLE
添加防火墙入站支持

### ISSUE THREAD

**Issue by 0400H** [zmjack/PortProxyGUI#16]
在配置好以下端口转发规则的情况下,只能本地访问,局域网无法访问:
```
v4tov4 *:18000 -> localhost:8000
```

经检查是默认开启的系统防火墙导致的，添加以下防火墙规则后可以工作:
```
netsh advfirewall firewall add rule name="PortProxy{*:18000,localhost:8000}" dir=in action=allow protocol=TCP localport=18000
```

1. 希望增加对防火墙的支持。
例如在添加端口转发规则时，有规则选项或全局选项可以选择是否添加防火墙的入站规则，并在开启和禁用时自动添加和删除规则。
2. 希望能在明确的位置提醒使用人员，当在软件中开启端口转发后，即使关闭软件，规则仍旧生效。

**Comment by zmjack** [comment]
目前不会增加防火墙配置功能，这将会增加软件复杂度。

需要了解到，PortProxy 属于系统服务，PortProxyGUI 只是提供了可选的管理入口。

**Comment by 0400H** [comment]
> 目前不会增加防火墙配置功能，这将会增加软件复杂度。
> 
> 需要了解到，PortProxy 属于系统服务，PortProxyGUI 只是提供了可选的管理入口。

新功能的增加肯定会增加软件的复杂度，最简实现仅需要添加两条指令和一个GUI开关。
`允许自动配置防火墙`功能是影响软件的`可用性`，而不是`锦上添花`，故此建议添加支持。

**Comment by leihao** [comment]
我赞同作者的想法,况且Windows自带防火墙也并不是唯一的可能防火墙,与其去适配一个防火墙,不如把这个情况写进FAQ中

**Comment by mr-mihu** [comment]
> > 目前不会增加防火墙配置功能，这将会增加软件复杂度。
> > 需要了解到，PortProxy 属于系统服务，PortProxyGUI 只是提供了可选的管理入口。
> 
> 新功能的增加肯定会增加软件的复杂度，最简实现仅需要添加两条指令和一个GUI开关。 功能是影响软件的，而不是，故此建议添加支持。`允许自动配置防火墙``可用性``锦上添花`

哥们，有没有找到其他代替的工具，支持的推荐一下，开发工具使用时候是自动配置防火墙的，切换到虚拟机内使用这个工具还需要手动配置防火墙，太繁琐了

**Comment by 0400H** [comment]
> > > 目前不会增加防火墙配置功能，这将会增加软件复杂度。
> > > 需要了解到，PortProxy 属于系统服务，PortProxyGUI 只是提供了可选的管理入口。
> > 
> > 
> > 新功能的增加肯定会增加软件的复杂度，最简实现仅需要添加两条指令和一个GUI开关。 功能是影响软件的，而不是，故此建议添加支持。`` 允许自动配置防火墙``可用性``锦上添花 ``
> 
> 哥们，有没有找到其他代替的工具，支持的推荐一下，开发工具使用时候是自动配置防火墙的，切换到虚拟机内使用这个工具还需要手动配置防火墙，太繁琐了

目前是手动输入指令凑合用的状态，实在嫌麻烦只能尝试修改源码丰衣足食。
