### ISSUE TITLE
1.3.0 版一切使用正常, 1.4.0 版怎么添加/修改/启用/禁用/删除条目, 程序都会报错呢

### ISSUE THREAD

**Issue by heeroyuyj** [zmjack/PortProxyGUI#17]
一直正常使用来着, 心血来潮更新了一下, 结果发现就出问题了 (测试了 PortProxyGUI.v1.4.0.NET35 和 PortProxyGUI.v1.4.0.NET6-x64) 都存在一样的问题

错误如下

`有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.InvalidOperationException: Control Service (iphlpsvc) ParamChange failed.
   at PortProxyGUI.Utils.PortPorxyUtil.ParamChange()
   at PortProxyGUI.SetProxy.button_Set_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

此时, 即便我打开 1.3.0 版本程序也没办法正常使用, 会提示当前配置只有新版本支持, 必须下载新版本才能打开程序, 无奈只能删了 文档 内的配置数据库, 才能重新使用 1.3.0 程序

**Comment by zmjack** [comment]
可能是 iphlpsvc 服务没有启用，检查一下服务。

下个版本会修复该问题。

**Comment by heeroyuyj** [comment]
我使用 windows 的 netsh interface portproxy 相关命令可以看到最新版程序的操作都是有效的, 但是就是每操作一下就会报个错, 看的有点那啥 😂

**Comment by zmjack** [comment]
已更新至 v1.4.1，试试新版本吧！

**Comment by YouveGotMeowxy** [comment]
@zmjack I was looking at the changes in https://github.com/zmjack/PortProxyGUI/commit/fe775680217f5aac647217d4ee4f47abbaeb6aa3

and am wondering what the _goal_ of handling the ip helper service change is?

Is it just to do a restart of the iphlpsrv? Or is there something "trickier" being done, like a pause and continue instead of a full restart of the service?

**Comment by zmjack** [comment]
@YouveGotMeowxy HI !

I don't know which line of code is confusing you, please point it out if you can.

The software does not have any operation to restart **IP Helper**.

In the new version, only the operation of **checking** is added. If the **IP Helper** service is not started, you can simply click on the prompt to start it.

---

You need to know that if the **IP Helper** service is not started, the port mapping will not take effect.

Port mapping table is stored in registry, if there is any change in it, we should notify **iphlpsvc** service.

---

To notify a service, the **SERVICE_CONTROL_PARAMCHANGE** permission is required and the service handle must have the **SERVICE_PAUSE_CONTINUE** access permission.

You can find some info at https://learn.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-controlservice .
(Ctrl+F: **SERVICE_CONTROL_PARAMCHANGE**)

**Comment by YouveGotMeowxy** [comment]
Hi :D 

> Port mapping table is stored in registry, if there is any change in it, we should notify **iphlpsvc** service.
> 
> To notify a service, the **SERVICE_CONTROL_PARAMCHANGE** permission is required and the service handle must have the **SERVICE_PAUSE_CONTINUE** access permission.

- I guess that's the part that is confusing me, rather than any particular line of the code; what does the "notify" (pause/continue) actually **_do_** to the service? As opposed to stopping and starting it (effectively a restart)?

I noticed while using the example from [this](https://learn.microsoft.com/en-us/dotnet/api/system.serviceprocess.servicecontroller.canpauseandcontinue?view=dotnet-plat-ext-8.0) page on the `iphlpsvc`: 

```
ServiceController sc = new ServiceController("Simple Service");
Console.WriteLine("Status = " + sc.Status);
Console.WriteLine("Can Pause and Continue = " + sc.CanPauseAndContinue);
Console.WriteLine("Can ShutDown = " + sc.CanShutdown);
Console.WriteLine("Can Stop = " + sc.CanStop);
```

The line that tells `Can Pause and Continue` says `false`. So, I'm confused about if your code tries to pause and continue the service, or what? lol

- Also, is there any particular reason you're using the WinAPI to handle the service over the .NET native functions?

**Comment by zmjack** [comment]
Unfortunately **ServiceController** doesn't provide a **PARAMCHANGE** call wrapper from C#.

**PARAMCHANGE** means that to notify the service to reread its startup parameters without stopping or restarting.

---

If you restart it, the established connection will be disconnected.

However, **PARAMCHANGE** will not cause this problem.

It is similar to hot reload.

---

**ServiceController** only provides the most basic functions.

If you want to query whether a service supports **PARAMCHANGE**, try the following **C++** code:

```cpp
#include <iostream>
#include <Windows.h>
using namespace std;

int main()
{
    auto service = L"iphlpsvc";

    auto hManager = OpenSCManager(NULL, NULL, GENERIC_READ);
    if (hManager == NULL)
    {
        cerr << "error" << endl;
        return 0;
    }

    auto hService = OpenService(hManager, service, SERVICE_QUERY_STATUS);
    if (hService == NULL)
    {
        CloseServiceHandle(hManager);
        cerr << "error" << endl;
        return 0;
    }

    auto status = (LPSERVICE_STATUS)malloc(sizeof(SERVICE_STATUS));
    QueryServiceStatus(hService, status);

    cout
        << "ACCEPT_PARAMCHANGE: "
        << ((status->dwControlsAccepted & SERVICE_ACCEPT_PARAMCHANGE) > 0)
        << endl;

    CloseServiceHandle(hService);
    CloseServiceHandle(hManager);

    return 0;
}
```

Click on the link for more details on **SERVICE_STATUS**.
https://learn.microsoft.com/en-us/windows/win32/api/winsvc/ns-winsvc-service_status
(Ctrl+F: **SERVICE_ACCEPT_PARAMCHANGE**)

**Comment by YouveGotMeowxy** [comment]
> If you restart it, the established connection will be disconnected.

aha! That's the main thing that I wasn't aware of. That makes sense now. Thanks! :)

**Comment by YouveGotMeowxy** [comment]
@zmjack Sorry for the spam, lol, but do you happen to have a .exe compiled for that c++ code? I don't really know c++ and also I don't think I installed all the c++ stuff when I installed visual studio, but I'd love to have a little utility like that to check with.

Update:

Nevermind! I plugged the code into AI and it immediately gave me working code that I could use in Linq Pad. Crazy! LOL

![image](https://github.com/zmjack/PortProxyGUI/assets/39491297/d517726e-7dd8-481d-997d-42ada6cb6855)

**Comment by zmjack** [comment]
WOW !

Have a nice day.

**Comment by YouveGotMeowxy** [comment]
Just noticed this when playing with servicecontroller, is it essentially the same as using paramchange?

![image](https://github.com/zmjack/PortProxyGUI/assets/39491297/2f2a3ff9-3f0b-4611-bb22-44b866c437ff)

**Comment by zmjack** [comment]
No, it just refreshes the cached states.

---

For example, when the service is running, instantiate a **ServiceController,** it's status is **Running.**

At this point, you change the status of the service in the service panel to **Stoped.**

But the status of the instantiated ServiceController is still **Running** until you refresh it.

---

You can write some simple code to verify it.

**Comment by zmjack** [comment]
I'm going to close this issue as it's already resolved.
