### ISSUE TITLE
兄弟，怎么变中文啊？

### ISSUE THREAD

**Issue by liupeng9030** [zmjack/PortProxyGUI#18]
看到里面有zh-CN的文件夹，而且我一直在用中文版的V1.0.1.0版本的程序。
现在默认是英文的，怎么变成中文？

**Comment by zmjack** [comment]
UI 默认显示语言 跟随 系统显示语言，并没有提供修改的设置 😨。

**Comment by liupeng9030** [comment]
那就奇怪了，我本身系统就是中文的啊，而且之前用v1.0.1.0版本显示的也是中文，就最新的这个居然显示英文的，奇怪了

**Comment by zmjack** [comment]
使用的是什么版本的操作系统？

**Comment by liupeng9030** [comment]
win10企业版  64位

**Comment by zmjack** [comment]
装了一台全新系统，并没有出现该问题。😨
