### ISSUE TITLE
请问能增加一个最小化到任务栏的功能么 

### ISSUE THREAD

**Issue by lhj5426** [zmjack/PortProxyGUI#19]
这个软件真的好小巧好简单  一看就会用 
不过就是最小化不是在托盘而是在任务栏占用一个图标的位置有点难受
因为吧 开启
![image](https://github.com/zmjack/PortProxyGUI/assets/30548000/b90a7566-8d63-4ee4-a8d9-13d4dad01d24)
开启 转发之后 就基本不改动了 所以如果能让窗口消失在任务栏 静悄悄的呆在托盘里
![image](https://github.com/zmjack/PortProxyGUI/assets/30548000/f350f4de-27c8-478a-a4df-13184bfd5c22)
 就太好了  所以 试着来 问一下 开发者 可以  最小化到托盘么

**Comment by zmjack** [comment]
直接关掉好了，只需要在配置的时候打开，不需要一直让它运行。

**Comment by lhj5426** [comment]
> 直接关掉好了，只需要在配置的时候打开，不需要一直让它运行。

噢噢 也行 无感知  更棒 我试试

**Comment by zmjack** [comment]
看起来已经解决了，我准备关闭这个 Issue。如有需要再重新打开。😀
