### ISSUE TITLE
PortProxyGUI v1.0.5.0 之后的版本不兼容 Windows Server Core  2022

### ISSUE THREAD

**Issue by X96A33** [zmjack/PortProxyGUI#21]
![屏幕截图 2024-06-01 032322](https://github.com/zmjack/PortProxyGUI/assets/140457636/7ce07ee2-5613-4850-bb8f-81d9c15cf2c0)
经过测试，从 v1.1.0 开始到最新版本(v1.4.1)均不兼容 Windows Server Core  2022
v1.1.0 及以上版本运行后大约3秒后关闭，且在此过程中不会显示窗口 (已排除NET运行库问题)
而最后兼容此系统的版本完全可以正常使用，希望PortProxyGUI可以重新兼容此系统
(仅在Windows Server Core  2022进行测试，不确定Windows Server Core  2019或其它版本是否存在相同的问题)

**Comment by zmjack** [comment]
我在虚拟机中安装 Windows Server 2022 后使用，未能重现该问题。

是否可能是其他原因导致？

![image](https://github.com/zmjack/PortProxyGUI/assets/24598247/c7aff9ac-3622-4e1c-9a91-1c8891c11c29)

**Comment by X96A33** [comment]
我所使用的 Windows Server 2022 为核心版本 (未安装GUI) ，我也尝试过重新安装系统和在其它计算机进行测试，问题依旧
(我在以下版本的系统中进行过测试，均存在同样问题)
![屏幕截图 2024-06-04 023239](https://github.com/zmjack/PortProxyGUI/assets/140457636/a0b009da-eb78-4c82-8102-d864aaa5b826)
![屏幕截图 2024-06-04 023524](https://github.com/zmjack/PortProxyGUI/assets/140457636/de5f21a1-dbfe-4263-80e7-92ea6f52e4d1)

**Comment by zmjack** [comment]
已确认该问题。

原因是该版本系统缺少使用的字体（`Microsoft Sans Serif (TrueType)`）文件（`micross.ttf`）。

<br/>

可使用以下方法临时解决：

1. 复制字体文件 `micross.ttf` 至 `C:\Windows\Fonts`；

2. 添加注册表项

   位置：`HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts`

   项名：`Microsoft Sans Serif (TrueType)`

   项值：`micross.ttf`

**Comment by zmjack** [comment]
试下新版本吧。

:gift_heart: v1.4.2

**Comment by X96A33** [comment]
谢谢
