### ISSUE TITLE
建议加上启用禁用映射规则

### ISSUE THREAD

**Issue by jvfan** [zmjack/PortProxyGUI#5]
z 大好，我遇到了一个问题：

当我使用 PortProxyGUI 创建了一条规则，侦听 *:8080 连接 127.0.0.1:8080；
然后打开 docker-desktop（WSL2 后端）运行一个跑在 127.0.0.1:8080 上的服务，总会提示端口占用：
(HTTP code 500) server error - Ports are not available: listen tcp 127.0.0.1:8080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

而先开 docker 服务，再创建映射规则就不会出问题；
所以每次开机我都需要删除 PortProxyGUI 上的规则，再开 docker 服务，再添加映射规则，这很繁琐，所以希望 z 大加入启用禁用规则的能力；

另外，强烈建议提供 .net4.5 版本的下载，win10 上开箱即用；

**Comment by zmjack** [comment]
好建议，感谢反馈！

下个版本会加入这些功能：
- 规则开关
- .NET 4.5 支持

**Comment by zmjack** [comment]
@jvfan 新版本已发布，欢迎试用！
上述功能已提供支持。

**Comment by jvfan** [comment]
> @jvfan 新版本已发布，欢迎试用！
> 上述功能已提供支持。

非常好用，感谢您！
