### ISSUE TITLE
有一个小小的问题

### ISSUE THREAD

**Issue by chalan630** [zmjack/PortProxyGUI#6]
我平时借助此工具进行wsl端口映射，IP地址是会一直变化的。修改功能中的监听地址不支持修改，想问一下能否实现监听地址和连接地址一样可以修改的功能。

**Comment by zmjack** [comment]
下个版本安排上

**Comment by zmjack** [comment]
@chalan630 ”转发类型、监听地址、监听端口“的修改功能已在新版本（**v1.1.1+**）支持。

**Comment by chalan630** [comment]
感谢
